project:
  type: book

book:
  title: "Systems Programming Languages"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - setup.qmd
    - part: "C++"
    - resources.qmd
  page-navigation: true
  downloads: pdf

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


number-depth: 2
